version: "3.8"

services:
  authentication-service:
    build:
      context: ./authentication_service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_SERVICE_URL=http://localhost:8191
    networks:
      - my-network
    volumes:
      - ./authentication_service:/app

  dashboard:
    build:
      context: ./dashboard_service
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    networks:
      - my-network
    environment:
      - DATABASE_SERVICE_URL=http://localhost:8191
      - EXPENSE_DETAILS_SERVICE_URL=http://localhost:3000
      - EXPENSE_MANAGEMENT_SERVICE_URL=http://localhost:3050
    volumes:
      - ./dashboard_service:/app

  database:
    build:
      context: ./database_service
      dockerfile: Dockerfile
    ports:
      - "8191:5000"
    networks:
      - my-network
    volumes:
      - ./database_service:/app

  expense-details:
    build:
      context: ./expense_details_service
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    networks:
      - my-network
    volumes:
      - ./expense_details_service:/app
    environment:
      - DATABASE_SERVICE_URL=http://localhost:8191

  expense-management:
    build:
      context: ./expense_management_service
      dockerfile: Dockerfile
    ports:
      - "3050:5000"
    networks:
      - my-network
    volumes:
      - ./expense_management_service:/app
    environment:
      - DATABASE_SERVICE_URL=http://localhost:8191
networks:
  my-network:
